# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='codigo',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
