# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_usuarios_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='adjunto',
            field=models.FileField(default=False, upload_to=b''),
        ),
    ]
