# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_solicitud_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
