# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_solicitud_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
